server:
  port: 4000
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/kill
    username: root
    password: cgl1403241032;
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
