server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2
    password: cgl1403241032;
    username: root
mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl