server:
  port: 6000
spring:
  application:
    name: order
  redis:
    host: 192.168.233.128
    timeout: 10000ms
  datasource:
    username: root
    password: cgl1403241032;
    url: jdbc:mysql://localhost:3306/kill
  rabbitmq:
    host: 192.168.233.128
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
    registry-fetch-interval-seconds: 5
